{
 "title": "SMS Frontend Overview",
 "description": "Metrics for the SMS application",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Average SMS Prediction Latency",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(sms_prediction_latency_seconds_sum[$__rate_interval]))/sum(rate(sms_prediction_latency_seconds_count[$__rate_interval]))",
     "legendFormat": "Average Latency"
    }
   ]
  },
  {
   "title": "SMS Prediction Latency Distribution",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(rate(sms_prediction_latency_seconds_bucket[$__rate_interval])) by (le)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "SMS Prediction Latency",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(\n  0.95,\n  sum(rate(sms_prediction_latency_seconds_bucket[$__rate_interval])) by (le)\n)",
     "legendFormat": "P95 Latency"
    }
   ]
  },
  {
   "title": "Spam Prediction ratio",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sms_predictions_spam_ratio", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "SMS Predictions over time",
   "type": "timeseries",
   "description": "Reports on the predictions over time",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "sum by (result) (rate(sms_predictions_total[$__rate_interval]))",
     "legendFormat": "{{result}}"
    }
   ]
  },
  {
   "title": "Page views rate",
   "type": "timeseries",
   "description": "Reports the per-device traffic.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "targets": [
    {
     "expr": "sum by (device_type) (rate(sms_page_views_total[$__rate_interval]))",
     "legendFormat": "{{device_type}}"
    }
   ]
  }
 ]
}