apiVersion: v1
kind: Service
metadata:
  name: model-service
spec:
  selector:
    app: model-service
  ports:
    - name: http
      port: {{ .Values.modelService.service.port }}
      targetPort: {{ .Values.modelService.service.port }}
  type: ClusterIP
